// Code generated by MockGen. DO NOT EDIT.
// Source: example/foobar.go

// Package example is a generated GoMock package.
package example

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockFooBar is a mock of FooBar interface.
type MockFooBar struct {
	ctrl     *gomock.Controller
	recorder *MockFooBarMockRecorder
}

// MockFooBarMockRecorder is the mock recorder for MockFooBar.
type MockFooBarMockRecorder struct {
	mock *MockFooBar
}

// NewMockFooBar creates a new mock instance.
func NewMockFooBar(ctrl *gomock.Controller) *MockFooBar {
	mock := &MockFooBar{ctrl: ctrl}
	mock.recorder = &MockFooBarMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFooBar) EXPECT() *MockFooBarMockRecorder {
	return m.recorder
}

// WithMap mocks base method.
func (m *MockFooBar) WithMap(arg1 map[string]int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WithMap", arg1)
}

// WithMap indicates an expected call of WithMap.
func (mr *MockFooBarMockRecorder) WithMap(arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithMap", reflect.TypeOf((*MockFooBar)(nil).WithMap), arg1)
}

// WithSlice mocks base method.
func (m *MockFooBar) WithSlice(arg1 []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WithSlice", arg1)
}

// WithSlice indicates an expected call of WithSlice.
func (mr *MockFooBarMockRecorder) WithSlice(arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithSlice", reflect.TypeOf((*MockFooBar)(nil).WithSlice), arg1)
}

// WithString mocks base method.
func (m *MockFooBar) WithString(arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WithString", arg1)
}

// WithString indicates an expected call of WithString.
func (mr *MockFooBarMockRecorder) WithString(arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithString", reflect.TypeOf((*MockFooBar)(nil).WithString), arg1)
}
